### ISSUE TITLE
GTA5 pretrained model missing

### ISSUE THREAD

**Issue by Erosinho13** [idiap/model-uncertainty-for-adaptation#6]
Thank you for sharing your work.

I'm interested in the GTA5 to Cityscapes training, but I've found in your README only the link to the Synthia pretrained checkpoint. I found the GTA5 pretrained checkpoint following the link provided by the [repository](https://github.com/ZJULearning/MaxSquareLoss) that you cite in your work (namely GTA5_source.pth at this [link](https://drive.google.com/file/d/1KP37cQo_9NEBczm7pvq_zEmmosdhxvlF/view)), but the test on Cityscapes after loading the parameters and without additional training iterations achieved very bad performances of only 0.5% miou, far from the 33.8% you declared in the paper. Moreover, I achieve only 2.5% miou even if I load the [Synthia_source checkpoint](https://drive.google.com/file/d/1wLffQRljXK1xoqRY64INvb2lk2ur5fEL/view) you provided in your repo, much less than the 40.3% of the paper. [Here](https://github.com/idiap/model-uncertainty-for-adaptation/blob/main/do_segm.py#L43) I see that you are loading a different model, probably because you are sharing the code for the Cityscapes to Cross-City experiments, but this checkpoint is not present in your repository anyway. I'm using your exact network for my experiments.

Are these the correct checkpoints? Could you please share the checkpoints of the pertaining phase on GTA5 that should achieve 33.8% miou and the final checkpoint after the application of your method that should achieve 45.1%?

I'd be grateful if you could provide at least these two checkpoints! Thank you.

**Comment by prabhuteja12** [comment]
Hi, 

Thank you for pointing this out. This is indeed a wrong link in the repo. I'm providing code for Cityscapes-NTHU exps here, and the pretrained model from the original [MaxSquares](https://github.com/ZJULearning/MaxSquareLoss) is https://drive.google.com/open?id=1QMpj7sPqsVwYldedZf8A5S2pT-4oENEn . This should give you the correct performance. 

I'm not sure which Synthia source checkpoint you mention, as i've not provided any. I used a different code base that is largely based on the [CRST](https://github.com/yzou2/CRST), and their pretrained models for both GTA/Synthia -> Cityscapes exps.
